# Generated by Django 4.2.2 on 2024-10-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manager', 'Может блокировать пользователей сервиса'), ('moderator', 'Может просматривать и редактировать любые уроки и курсы')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
