# Generated by Django 4.2.2 on 2024-10-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manager', 'Может блокировать пользователей сервиса')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.CreateModel(
            name='PayMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_payment', models.DateField(auto_now_add=True, verbose_name='дата оплаты')),
                ('method_payment', models.CharField(choices=[('C', 'наличные'), ('B', 'перевод')], max_length=1, verbose_name='метод оплаты')),
                ('sum_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма оплаты')),
                ('status_payment', models.CharField(choices=[('P', 'оплачен'), ('N', 'не оплачен')], default='N', max_length=1, verbose_name='статус оплаты')),
                ('course', models.ManyToManyField(blank=True, null=True, to='lms.course', verbose_name='Оплаченные курсы')),
                ('lesson', models.ManyToManyField(blank=True, null=True, to='lms.lesson', verbose_name='Оплаченные уроки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
