# Generated by Django 4.2.2 on 2024-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_lesson_avatar'),
        ('users', '0002_alter_user_options_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ManyToManyField(to='lms.course', verbose_name='Оплаченные курсы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ManyToManyField(to='lms.lesson', verbose_name='Оплаченные уроки'),
        ),
    ]
