# Generated by Django 4.2.2 on 2024-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='method_payment',
            field=models.CharField(choices=[('N', 'наличные'), ('B', 'перевод'), ('C', 'картой')], max_length=1, verbose_name='метод оплаты'),
        ),
    ]
