# Generated by Django 4.2.2 on 2024-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_payment_method_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', max_length=255, verbose_name='айди оплаты'),
            preserve_default=False,
        ),
    ]
