# Generated by Django 4.2.2 on 2024-10-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='token_auf',
        ),
    ]
