# Generated by Django 4.2.2 on 2024-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', max_length=255, verbose_name='id сессии'),
            preserve_default=False,
        ),
    ]
