version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod

  celery_beat:
    build:
      context: .
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Applying migrations...';
        python manage.py migrate &&
        echo 'Running load db.json' &&
        python manage.py loaddata db.json &&
        echo 'Starting Django server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    volumes:
      - .:/app

volumes:
  postgres_data: