# Generated by Django 5.1.1 on 2024-09-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название курса')),
                ('description', models.TextField(verbose_name='описание курса')),
                ('avatar', models.ImageField(upload_to='course/', verbose_name='превью')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('avatar', models.ImageField(upload_to='lesson/', verbose_name='превью')),
                ('video_link', models.URLField(verbose_name='ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='курс')),
            ],
        ),
    ]
