# Generated by Django 4.2.2 on 2024-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='превью'),
        ),
    ]
